---
- name: install nigix server
  hosts: all
  become: yes
  tasks:
   - name: install nginx using apt on Node server
     ansible.builtin.apt:
      name: nginx
      update_cache: yes
      state: present

