#Manual Steps:
#sudo apt update
#sudo apt install git  >>>  lets write a playbook
---
- name: Install Tree on Ubunut server Node
  become: yes
  hosts: all
  task: 
    - name: Installing Tree on ubunutNode
      ansible.builtin.apt:
        name: git, tree
        update_cache: true
        state: present