---
- name: install apcahe on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
   - name: update packages and install apache2
     ansible.builtin.apt:
        name: apache2
        state: present
   - name: enable and start apache service
     ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started

---
- name: install apcahe on redhat
  hosts: redhat
  become: yes
  tasks:
   - name: update packages and install apache2
     aansible.builtin.dnf:
       name: httpd
       state: present
   - name: enable and start httpd service
     ansible.builtin.systemd:
       name: httpd2
       enabled: yes
       state: started