---
- name: install lamp stack
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsupported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: update packages and install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: enable and start apache
      service:
        name: apache2
        enabled: yes
        state: started
    - name: install php packages
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        state: present
    - name: restart apache  #defnetly not a good practise if the server is restarts multiple times
      service:
        name: apache2
        state: restarted
    - name: copy info.php
      copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache
      service:
        name: apache2
        state: restarted




#Manual Steps:
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#sudo apt update
#sudo apt install apache2 -y
#sudo systemctl enable apache2
#sudo systemctl start apache2
#sudo apt install php libapache2-mod-php php-mysql
#sudo systemctl restart apache2

# create a file in /var/www/html/info.php with content <?php phpinfo(); ?>
#sudo systemctl restart apache2